### PR TITLE
 add redirect to correct xml namespace validation

### PR DESCRIPTION
**Pull request by mikelmaron**

### CODE REVIEW

**Comment by isc-rsingh** [comment]
This fix doesn't seem to be working. Can you test?

**Comment by mikelmaron** [comment]
Will investigate. It worked locally fine, perhaps some Jekyll config difference on GitHub

**Comment by seyfro** [comment]
doesnt work for me either - perhaps this has to do with TLS as all github requests are forwarded to https?

**Comment by isc-rsingh** [comment]
I figured out the site was being served from my other github account. Trying to fix that and get DNS pointed to the right place now.

**Comment by seyfro** [comment]
Thx! Please also check the links in the community section, which also seem to be broken - at least the Tools page which I hope can help me to validate my feed:

http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdemo.mapsmarker.com%2Fwp-content%2Fplugins%2Fleaflet-maps-marker-pro%2Fleaflet-georss.php%3Flayer%3D1

**Comment by mikelmaron** [comment]
Sorry, I don't follow the problem here. Looks like the validator found some issues with your feed, separate from the GeoRSS issues.
- Mikel Maron \* +14152835207 @mikel s:mikelmaron

**Comment by isc-rsingh** [comment]
Glad everything's working on this end again. @robertharm are you talking about http://www.georss.org/implementations.html as the tools page? All those links work for me. Oh I just looked at the bottom of the home page. I got rid of things that didn't work like the blog and mailing list.

**Comment by seyfro** [comment]
thanks for all your support - made my feeds valid again - wasnt related to the initial issue...

**Comment by isc-rsingh** [comment]
No problem. Thank you for the nudge to update the site a bit.

**Pull request merged**
